### ISSUE TITLE
Acuracia do modelo

### ISSUE THREAD

**Issue by rrfaria** [ItamarRocha/binary-bot#1]
Opa Itamar tudo bem?

encontrei seu repositorio e fiquei curioso.

Tu conseguiu quanto de acuracia no modelo?
Fez algum crossvalidation ?

fez algum backtest?

**Comment by ItamarRocha** [comment]
Opa, Boa tarde. Eu consegui uma média de 60% tanto no conjunto de teste quanto no conjunto de validação da rede. Como o modelo funciona meio que online, ele treina novamente em novos dados após 10 transações, então essa acurácia não é sempre a mesma, mas nos meus testes e validações a variação foi pouca, indo de 57% a 70%, mas geralmente no patamar de 60% mesmo. O projeto ainda está em construção e ainda tenho que elaborar algumas ferramentas pra mitigar o risco.  Acho que a rede ainda não está 100%. O trabalho ainda está em construção. Qualquer sugestão ou dúvida só falar. Valeu!

![image](https://user-images.githubusercontent.com/53613091/81105269-0ffdbc80-8eea-11ea-8499-d95f1e0ee197.png)
Um exemplo de acertos seguidos do modelo. Lembrando que nem sempre isso de fato acontece, mas nos testes feitos na prática a taxa de acerto variou de 55% a 60%.

**Comment by rrfaria** [comment]
Sugestão pra vc testar ... tenta ver alguma vps proxima do servidor da iqoption para reduzir o delay .. amazon tem serviço de 1 ano gratuito mas tem que tomar cuidado pra nao ultrapassar o limite se não sai caro... ou vc pode procurar uma vps com custo bom e que nao va aumentar com tempo porque isso realmente consome muito streaming de dados.

**Comment by rrfaria** [comment]
Ja tentou usar soros e martingale para tentar recuperar e alavancar?

**Comment by ItamarRocha** [comment]
Esse modelo ta aplicando martingale. Eu estou desenvolvendo pra swing trade agora e pesquisando outros métodos pra aplicar nesse problema. LSTM quebra um galho, mas é longe de ser ideal.
