### ISSUE TITLE
AttributeError: 'IQ_Option' object has no attribute 'api'

### ISSUE THREAD

**Issue by DiMiTriFrog** [ItamarRocha/binary-bot#17]
Any could help me?
When I trying to run the testing.py show the error:
`AttributeError: 'IQ_Option' object has no attribute 'api'`

**Comment by thangtranquang** [comment]
@DiMiTriFrog Please add "iq.connect() #connect to iqoption" after iq=IQ_Option("email","password") # YOU HAVE TO ADD YOUR USERNAME AND PASSWORD in iq.py

**Comment by ItamarRocha** [comment]
issue solved on #19
