### ISSUE TITLE
No work get_candles

### ISSUE THREAD

**Issue by ElLuigi** [ItamarRocha/binary-bot#20]
![image](https://user-images.githubusercontent.com/67555815/93671883-0cc03300-fa7d-11ea-9808-e800f7a8e0f1.png)

https://github.com/ItamarRocha/binary-bot/pull/19 not is the solucion!!

**Comment by Ananthageethan** [comment]
are you solved this error?

**Comment by kingmagatron** [comment]
This ofter happens when instument id is not correct or u didnt update opcode from api. using this iq.update_ACTIVES_OPCODE()
