### ISSUE TITLE
OTC?

### ISSUE THREAD

**Issue by ElLuigi** [ItamarRocha/binary-bot#24]
Hola, no esta funcionando en OTC

**Comment by lucasdobr15** [comment]
> Hola, no esta funcionando en OTC

Tente usar isso quando estiver em OTC (comigo não funcionou): 

>>> **Comando** >> python testing.py EURUSD-OTC 2 3

***(Tipo de Moeda em OTC)***: GBPUSD-OTC --- EURJPY-OTC --- AUDUSD-OTC
***(Valor da aposta $)***: 2
***(Quantidade de Martingale)***: 3
