### ISSUE TITLE
ERRO: False Cannot purchase an option (the asset is not available at the moment).

### ISSUE THREAD

**Issue by lucasdobr15** [ItamarRocha/binary-bot#26]
Já instalei todos os pacotes necessários e a api esta na ultima versão lançada, já inclui meu login na api iq.py,

Porém ao executar o comando> python testing.py

A api loga normalmente, mas em determinado momento, a api retorna este erro
![erro](https://user-images.githubusercontent.com/12130053/111009137-8886a280-8371-11eb-8be6-fb64fd9e4b41.jpg)

Como deveria proceder para corrigir este erro?

**Comment by ItamarRocha** [comment]
Provavelmente a opção que você escolheu tava fechada no momento. Checa isso no site antes de rodar.

**Comment by lucasdobr15** [comment]
Assim então provavelmente seja por isso, o bot seu opera em OTC?

Outra coisa, quando tento este comando

$ python testing.py GBPUSD 2 3

retorna esse erro  **invalid request** seria algum erro da api? eu sei que o 2 é $amount e o 3 é a quantidade de gale né e mesmo usando outras currency nesse comando ainda continua dando invalid request suponho que o erro seja na api? ou então é o bot que não funciona em OTC né
![Screenshot_2](https://user-images.githubusercontent.com/12130053/111019022-5b4eea00-839b-11eb-8c15-bbc1bcde862e.jpg)

**Comment by lucasdobr15** [comment]
Boa noite, só passando aqui para dar um feedback, o bot está com bastante precisão nas analises, dando wins, já solucionei os demais problemas que vinha enfrentando, se quiser já pode encerrar este ticket, obrigado por compartilhar este projeto é de grande valia para nós! Deus te abençoe ;)

**Comment by ItamarRocha** [comment]
Ok. Se tiver alguma melhora para adicionar ao projeto, só fazer um pull request. Obrigado pelo feedback.
