### ISSUE TITLE
I can't start

### ISSUE THREAD

**Issue by victalejo** [ItamarRocha/binary-bot#3]
![image](https://user-images.githubusercontent.com/51432115/82720736-f5fb0280-9c7b-11ea-80e9-fb02f1c6801e.png)

I have this error when starting the testing.py file

**Comment by ItamarRocha** [comment]
Seems like a problem in detecting your GPU.  Try this links.
Related problem:
https://github.com/tensorflow/tensorflow/issues/255
Tensorflow install with GPU support:
https://www.tensorflow.org/install/gpu
