### ISSUE TITLE
Error cloning API

### ISSUE THREAD

**Issue by victalejo** [ItamarRocha/binary-bot#4]
![image](https://user-images.githubusercontent.com/51432115/82870403-7ed0a300-9ef5-11ea-905a-357ac6201327.png)

This appears, when I try to clone the IQ option API, using the command $ pip install -U git + git: //github.com/Lu-Yi-Hsun/iqoptionapi.git

**Comment by ItamarRocha** [comment]
They released a new version. Check it out. My repository is currently outdated. I intend to make some fixes soon.
