### ISSUE TITLE
Abertura do programa

### ISSUE THREAD

**Issue by comodus-six** [ItamarRocha/binary-bot#5]
Boa tarde. tentei executar o programa do bot, porem nao foi possivel, o mesmo nao apresenta nenhum retorno.
![image](https://user-images.githubusercontent.com/67558178/85956139-26f4e400-b95a-11ea-91de-1606d51ee5fb.png)

**Comment by ItamarRocha** [comment]
colocasse email e login? baixou a api atualizada? Todos os pacotes ok?

**Comment by comodus-six** [comment]
sim,api atualizada, e todos os pacotes. tudo normal.

**Comment by ItamarRocha** [comment]
Nenhum erro? Ou warning?

**Comment by comodus-six** [comment]
nda, fiz a atualizacao dos pacotes e nao acontece nada.
![image](https://user-images.githubusercontent.com/67558178/85961810-5b30ca80-b983-11ea-9be1-f9e87ce235fa.png)

porem quando executo pelo training dai aparece todos os comandonao acrregados
![image](https://user-images.githubusercontent.com/67558178/85961848-8a473c00-b983-11ea-92af-dbb43c877b5c.png)

**Comment by ItamarRocha** [comment]
Então, você tem que rodar o testing.py. o IQ e o Training são chamados pelo
testing.
