### ISSUE TITLE
problema SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by lukefeix** [ItamarRocha/binary-bot#8]
Fala amigo beleza?
instalei todas as dependencias mas esta dando esse erro e não consegui resolver 
consegue ajudar?
![image](https://user-images.githubusercontent.com/67929862/86649321-065f0680-bfb8-11ea-8d85-70a2e113b2bb.png)

**Comment by ItamarRocha** [comment]
f strings estão disponíveis a partir do python 3.6. Cheque sua versão
digitando: Python no terminal.
