### ISSUE TITLE
Adição de método connect ao arquivo iq.py

### ISSUE THREAD

**Issue by jeanmacena** [ItamarRocha/binary-bot#9]
No arquivo IQ.py, na linha 20, acredito ser necessário adicionar a ação iq.connect() para evitar "AttributeError: 'IQ_Option' object has no attribute 'api'". Localmente para mim, foi necessário para estabelecer a conexão com o serviço. O método em questão retorna um True ou False para o pedido de conexão podendo validar o sucesso ou não.

**Comment by gabcarvalhogama** [comment]
Aqui também foi necessário adicionar o connect. Estava retornando erro.
![image](https://user-images.githubusercontent.com/8550468/91326262-80cb2c00-e79a-11ea-8ba4-79e2d75d48bc.png)

**Comment by ItamarRocha** [comment]
Issue solved on #19
